<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('menu')->insert([
            [
                'id_menu' => 1,
                'nama' => 'Geprek Hemat',
                'deskripsi' => 'Ayam geprek pedas dengan nasi, porsi hemat cocok untuk sehari-hari.',
                'harga' => 10000.00,
                'harga_beli' => 6000.00,
                'diskon' => 0,
                'is_paket' => false,
                'stok' => 50,
                'kategori' => 'geprek',
                'gambar' => 'ayamgeprek.jpg',
                'dibuat_pada' => '2025-11-02 01:19:54',
            ],
            [
                'id_menu' => 2,
                'nama' => 'Geprek Jumbo',
                'deskripsi' => 'Porsi besar ayam geprek dengan rasa mantap, bikin kenyang lebih lama.',
                'harga' => 14000.00,
                'harga_beli' => 8500.00,
                'diskon' => 0,
                'is_paket' => false,
                'stok' => 50,
                'kategori' => 'geprek',
                'gambar' => 'geprekjumbo.jpg',
                'dibuat_pada' => '2025-11-02 01:21:11',
            ],
            [
                'id_menu' => 3,
                'nama' => 'Crispy Hemat',
                'deskripsi' => 'Ayam crispy renyah dengan nasi, pas buat kantong pelajar.',
                'harga' => 9000.00,
                'harga_beli' => 5500.00,
                'diskon' => 0,
                'is_paket' => false,
                'stok' => 50,
                'kategori' => 'crispy',
                'gambar' => 'crispyhemat.webp',
                'dibuat_pada' => '2025-11-02 01:21:35',
            ],
            [
                'id_menu' => 4,
                'nama' => 'Crispy Jumbo',
                'deskripsi' => 'Ayam crispy ukuran jumbo, garing di luar lembut di dalam.',
                'harga' => 13000.00,
                'harga_beli' => 8000.00,
                'diskon' => 0,
                'is_paket' => false,
                'stok' => 50,
                'kategori' => 'crispy',
                'gambar' => 'crispyjumbo.webp',
                'dibuat_pada' => '2025-11-02 01:21:59',
            ],
            [
                'id_menu' => 5,
                'nama' => 'Gangnam Hemat',
                'deskripsi' => 'Ayam saus Korea rasa gurih manis pedas, paket hemat.',
                'harga' => 12000.00,
                'harga_beli' => 7500.00,
                'diskon' => 0,
                'is_paket' => false,
                'stok' => 50,
                'kategori' => 'gangnam',
                'gambar' => 'gangnamhemat.webp',
                'dibuat_pada' => '2025-11-02 01:22:31',
            ],
            [
                'id_menu' => 6,
                'nama' => 'Gangnam Jumbo',
                'deskripsi' => 'Ayam saus Korea porsi besar, cocok untuk yang doyan banget.',
                'harga' => 16000.00,
                'harga_beli' => 10000.00,
                'diskon' => 0,
                'is_paket' => false,
                'stok' => 50,
                'kategori' => 'gangnam',
                'gambar' => 'gangnamjumbo.webp',
                'dibuat_pada' => '2025-11-02 01:23:02',
            ],
            [
                'id_menu' => 7,
                'nama' => 'Gangnam Chicken Double',
                'deskripsi' => 'Dua potong ayam saus Korea lezat, puas buat sharing berdua.',
                'harga' => 20000.00,
                'harga_beli' => 12000.00,
                'diskon' => 0,
                'is_paket' => false,
                'stok' => 50,
                'kategori' => 'gangnam',
                'gambar' => 'gangnamdouble.webp',
                'dibuat_pada' => '2025-11-02 01:32:59',
            ],
            [
                'id_menu' => 8,
                'nama' => 'Paha Bawah',
                'deskripsi' => 'Potongan paha bawah ayam goreng gurih, nikmat disantap kapan saja.',
                'harga' => 9000.00,
                'harga_beli' => 5500.00,
                'diskon' => 0,
                'is_paket' => false,
                'stok' => 50,
                'kategori' => 'tambahan',
                'gambar' => 'pahabawah.webp',
                'dibuat_pada' => '2025-11-02 01:29:34',
            ],
            [
                'id_menu' => 9,
                'nama' => 'Sayap',
                'deskripsi' => 'Sayap ayam goreng renyah, cocok buat camilan atau tambahan lauk.',
                'harga' => 9000.00,
                'harga_beli' => 5000.00,
                'diskon' => 0,
                'is_paket' => false,
                'stok' => 50,
                'kategori' => 'tambahan',
                'gambar' => 'sayap.webp',
                'dibuat_pada' => '2025-11-02 01:29:59',
            ],
            [
                'id_menu' => 10,
                'nama' => 'Paha Atas',
                'deskripsi' => 'Paha atas ayam goreng empuk dengan cita rasa gurih.',
                'harga' => 12000.00,
                'harga_beli' => 7000.00,
                'diskon' => 0,
                'is_paket' => false,
                'stok' => 50,
                'kategori' => 'tambahan',
                'gambar' => 'pahaatas.webp',
                'dibuat_pada' => '2025-11-02 01:30:27',
            ],
            [
                'id_menu' => 11,
                'nama' => 'Dada',
                'deskripsi' => 'Daging dada ayam goreng lezat, potongan besar bikin puas.',
                'harga' => 12000.00,
                'harga_beli' => 7000.00,
                'diskon' => 0,
                'is_paket' => false,
                'stok' => 50,
                'kategori' => 'tambahan',
                'gambar' => 'dada.webp',
                'dibuat_pada' => '2025-11-02 01:30:48',
            ],
            [
                'id_menu' => 12,
                'nama' => 'Le Minerale 600ml',
                'deskripsi' => 'Air mineral segar untuk menemani makanmu.',
                'harga' => 4000.00,
                'harga_beli' => 2000.00,
                'diskon' => 0,
                'is_paket' => false,
                'stok' => 100,
                'kategori' => 'minuman',
                'gambar' => 'leminerale.webp',
                'dibuat_pada' => '2025-11-02 01:31:24',
            ],
            [
                'id_menu' => 13,
                'nama' => 'Teh Pucuk 350ml',
                'deskripsi' => 'Teh manis menyegarkan, pas banget buat makan siang.',
                'harga' => 4000.00,
                'harga_beli' => 2500.00,
                'diskon' => 0,
                'is_paket' => false,
                'stok' => 100,
                'kategori' => 'minuman',
                'gambar' => 'tehpucuk.webp',
                'dibuat_pada' => '2025-11-02 01:32:01',
            ],
            // ========== MENU PAKET ==========
            [
                'id_menu' => 14,
                'nama' => 'Paket Sultan',
                'deskripsi' => 'Paket Sultan bikin kenyang maksimal! Geprek Jumbo + Dada Ayam + Teh Pucuk.',
                'harga' => 27900.00,
                'harga_beli' => 0, // dihitung dari komponen
                'diskon' => 0,
                'is_paket' => true,
                'stok' => 30,
                'kategori' => 'paket',
                'gambar' => 'geprekjumbo.jpg',
                'dibuat_pada' => now(),
            ],
            [
                'id_menu' => 15,
                'nama' => 'Paket Pelajar',
                'deskripsi' => 'Pilihan ramah kantong tapi nikmat. Crispy Hemat + Teh Pucuk.',
                'harga' => 11900.00,
                'harga_beli' => 0,
                'diskon' => 0,
                'is_paket' => true,
                'stok' => 30,
                'kategori' => 'paket',
                'gambar' => 'crispyhemat.webp',
                'dibuat_pada' => now(),
            ],
            [
                'id_menu' => 16,
                'nama' => 'Paket Hemat',
                'deskripsi' => 'Perpaduan pas untuk ngemil sedap! Gangnam Hemat + Le Minerale.',
                'harga' => 14900.00,
                'harga_beli' => 0,
                'diskon' => 0,
                'is_paket' => true,
                'stok' => 30,
                'kategori' => 'paket',
                'gambar' => 'gangnamhemat.webp',
                'dibuat_pada' => now(),
            ],
            [
                'id_menu' => 17,
                'nama' => 'Paket Puas',
                'deskripsi' => 'Makan puas bayar pas! Geprek Hemat + Sayap + Teh Pucuk.',
                'harga' => 19900.00,
                'harga_beli' => 0,
                'diskon' => 0,
                'is_paket' => true,
                'stok' => 30,
                'kategori' => 'paket',
                'gambar' => 'ayamgeprek.jpg',
                'dibuat_pada' => now(),
            ],
        ]);

        // ========== KOMPOSISI PAKET ==========
        DB::table('paket_komposisi')->insert([
            // Paket Sultan (14) = Geprek Jumbo (2) + Dada (11) + Teh Pucuk (13)
            ['id_menu_paket' => 14, 'id_menu_komponen' => 2,  'jumlah' => 1],
            ['id_menu_paket' => 14, 'id_menu_komponen' => 11, 'jumlah' => 1],
            ['id_menu_paket' => 14, 'id_menu_komponen' => 13, 'jumlah' => 1],

            // Paket Pelajar (15) = Crispy Hemat (3) + Teh Pucuk (13)
            ['id_menu_paket' => 15, 'id_menu_komponen' => 3,  'jumlah' => 1],
            ['id_menu_paket' => 15, 'id_menu_komponen' => 13, 'jumlah' => 1],

            // Paket Hemat (16) = Gangnam Hemat (5) + Le Minerale (12)
            ['id_menu_paket' => 16, 'id_menu_komponen' => 5,  'jumlah' => 1],
            ['id_menu_paket' => 16, 'id_menu_komponen' => 12, 'jumlah' => 1],

            // Paket Puas (17) = Geprek Hemat (1) + Sayap (9) + Teh Pucuk (13)
            ['id_menu_paket' => 17, 'id_menu_komponen' => 1,  'jumlah' => 1],
            ['id_menu_paket' => 17, 'id_menu_komponen' => 9,  'jumlah' => 1],
            ['id_menu_paket' => 17, 'id_menu_komponen' => 13, 'jumlah' => 1],
        ]);
    }
}